# СТАНЦІЇ

### 1. Створення станції (Київ)
POST http://localhost:3000/stations
Content-Type: application/json

{
  "name": "Kyiv Central",
  "city": "Kyiv",
  "coordinates": { "lat": 40.50 , "lon": 30.52 },
  "contact": { "email": "kyiv@eco.ua", "phone": "+380501234567" },
  "measurements": ["pm2.5", "temperature"]
}


### 1b. Створення станції (Львів)
POST http://localhost:3000/stations
Content-Type: application/json

{
  "name": "Lviv West",
  "city": "Lviv",
  "coordinates": { "lat": 49.84, "lon": 24.03 },
  "contact": { "email": "lviv@eco.ua", "phone": "+380671234567" },
  "measurements": ["co2", "humidity"]
}


### 2. Отримання всіх станцій
GET http://localhost:3000/stations


### 3. Отримання станції за ID
GET http://localhost:3000/stations/68dce0d34ffe43790bc6ac42


### 4. Оновлення станції
PUT http://localhost:3000/stations/68dce0d34ffe43790bc6ac42
Content-Type: application/json

{
  "city": "Lviv",
  "contact": { "email": "contact@eco.ua" }
}

### 5. Видалення станції
DELETE http://localhost:3000/stations/68dce0d34ffe43790bc6ac42


### 6. Видалення всіх станцій
DELETE http://localhost:3000/stations

# AIR QUALITY


### 1. Створення запису якості повітря
POST http://localhost:3000/airquality/68dce1254ffe43790bc6ac4a
Content-Type: application/json

{
  "pm25": 25,
  "pm10": 30,
  "co2": 410,
   "o3": 120,
  "no2": 80,
  "temperature": 22,
  "humidity": 45
}

### 2. Отримання всіх записів якості повітря
GET http://localhost:3000/airquality/


### 3. Отримання запису якості повітря за ID
GET http://localhost:3000/airquality/


### 4. Оновлення запису якості повітря
PUT http://localhost:3000/airquality/
Content-Type: application/json

{
  "pm25": 50,
  "co2": 460
}


### 5. Видалення запису якості повітря
DELETE http://localhost:3000/airquality/


### 6. Видалення всіх записів якості повітря
DELETE http://localhost:3000/airquality
